name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *' # every hour, UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace AstronomyAPI credentials in JS
        run: |
          sed -i "s/APP_ID/${{ secrets.APP_ID }}/g" tracker.js
          sed -i "s/APP_KEY/${{ secrets.APP_KEY }}/g" tracker.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
