name: Astronomy Tracker Update

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Clone repo using GH_TOKEN
        run: |
          git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} repo
          cd repo

          # Replace credentials
          sed -i "s/APP_ID/${{ secrets.APP_ID }}/g" tracker.js
          sed -i "s/APP_KEY/${{ secrets.APP_KEY }}/g" tracker.js

          # Commit and push
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add tracker.js
          git commit -m "Inject AstronomyAPI credentials" || echo "No changes to commit"
          git push origin main
